# URL
#url = https://qafe.buktec.co.in/login
#url = https://uatfe.buktec.co.in/login
url = https://app.thebuktec.com/login


# Login Credential
#accountcode = akashgirase018@gmail.com
#username = Akash88
#password = Akash@123

accountcode = 10000166
username = shubham123
password = Shubhu@09

#accountcode = 10000001
#username = pratyushjanghel
#password = Max@admin112


# Select Entity for use
entityname = S


# Snapshot Creation
snapshotdate = 10-12-2024
InvoiceNum = 2342765
TotalAmount = 5000
PartyName = Automate Snapshot
PartyGST = 23AAACH7409R1Z9
GSTAmt = 300
TDSpercent = 3

# Selected snapshot delete
Snapshotselection = EX Inventory 3

# Bulk upload
Bulkuploadfilepath = C:\\Users\\DELL\\OneDrive\\Desktop\\Invoices\\4075.pdf
Bulkuploadfilepath = C:\\Users\\DELL\\OneDrive\\Desktop\\Invoices\\4080.pdf

# Excel Import
Excelfilepath = C:\\Users\\DELL\\OneDrive\\Documents\\Buktec-Snapshot-Excel-Import-Sample (1).xlsx
InventoryExcelPath = C:\\Users\\DELL\\OneDrive\\Documents\\Buktec-Snapshot-Excel-Import-Inventory-Sample (14).xlsx

#Reimbursement Excel Import
ReimbursementExcelImportpath = C:\\Users\\DELL\\OneDrive\\Documents\\Buktec-Reimbursement-Excel-Import-Sample.xlsx

# Banking Module
addbank = Axis Bank
selectbanktype = Current Account
bankaccountname = shubham
bankaccountnumber = 34583082053364
bankledger = bank

# Moneylink Bank selection
Selectbank = 	Kotak Mahindra Bank

# Reports module
Exportsfields = TDS Details
selectbankforexport = IDBI Bank 646
Timeperiod = Since Beginning

# My Account details Modify
AccountName = ShubhamW
MobileNumber = 9860437894
GSTNumber = 29AEGPB5220M1ZT

# Entity for update
Entityselection = New123
Entitynameforupdate = New

# User for update
Userselection = otp
